try:
    num = input('Say Hello: ') 
except Exception as e:
    print(f'Error: {e}')
    